export const lesson = {
  number: "7.3.2",
  title: "Contract Closure Documentation: Invoices, Certificates, Warranties, Records, Archive",
  screens: [
    {
      id: "hook",
      tab: "Move-out logic",
      type: "reveal",
      kicker: "Screen 1 — Hook",
      headline: "Moving out of a rental apartment isn't finished the moment you hand back the keys.",
      lead: "The landlord inspects for damage, releases your security deposit once satisfied, and keeps a file of the lease, the move-out inspection, and any correspondence in case a dispute ever comes up later.",
      heading: "Moving out of a rental apartment isn't finished the moment you hand back the keys. The landlord inspects for damage, releases your security deposit once satisfied, and keeps a file of the lease, the move-out inspection, and any correspondence in case a dispute ever comes up later.",
      cta: "Reveal the logic",
      image: "rental-move-out",
      reveal: {
        title: "Contract closure runs on the exact same logic",
        text: "Contract closure runs on the exact same logic, at a much larger scale. With the work verified and accepted, the commercial tail follows in order — the final invoice is paid against verification, and retainage goes home.",
        image: "rental-move-out",
      },
    },
    {
      id: "invoice",
      tab: "Invoice & retainage",
      type: "reveal",
      kicker: "Screen 2 — The Final Invoice and Retainage",
      headline: "The seller's final invoice doesn't just get paid. It gets checked.",
      heading: "The seller's final invoice doesn't just get paid. It gets checked.",
      cta: "Reveal the discipline",
      image: "invoice-retainage",
      reveal: {
        title: "The Final Invoice and Retainage",
        text: "The final invoice is checked against three things before payment: the contract's price and payment terms, the record of accepted work, and the change-order history — every approved change priced in, every declined one absent. On a firm-fixed-price contract this is largely a confirmation exercise; on cost-reimbursable or time-and-materials contracts it's a genuine audit of allowable costs and rates against the agreement — exactly why those contract types impose more administrative burden at closure. Two disciplines matter here. First, no final payment over an open dispute — payment is the buyer's last leverage, and the contract's natural pressure toward settling claims first. Second, retainage — the percentage of progress payments many contracts withhold until satisfactory completion — is released at acceptance: holding a vendor's retainage after their work has been formally accepted is not prudence, it's a breach of the buyer's own obligations, and it poisons the relationship the performance record is about to memorialize.",
        image: "invoice-retainage",
      },
      quiz: {
        question: "Scenario: A vendor's work is formally accepted on a project. Two weeks later, the buyer still hasn't released the retainage that was withheld throughout the contract, reasoning that it's safer to hold onto it a little longer “just in case.” What is the issue with this approach?",
        answers: [
          "There is no issue — holding retainage a bit longer after acceptance is a prudent precaution",
          "Retainage is meant to be released at acceptance — holding it afterward is not prudence, it's a breach of the buyer's own obligations, and it damages the relationship",
          "The issue is only that retainage should have been released before acceptance, not after",
          "There is no issue, since retainage release timing is entirely at the buyer's discretion regardless of acceptance",
        ],
        correct: 1,
        correctFeedback: "Correct! Once work is formally accepted, retainage is meant to go home — holding it longer “just in case” isn't caution, it's a breach of the buyer's own contractual obligations, and it damages the exact relationship the performance record is about to document.",
        incorrectFeedback: "Reconsider — retainage is specifically tied to satisfactory completion, so release before acceptance would be premature; and release timing isn't purely discretionary — acceptance is the trigger.",
      },
    },
    {
      id: "documents",
      tab: "Three documents",
      type: "accordion",
      kicker: "Screen 3 — Three Documents, Three Different Futures",
      headline: "Three Documents, Three Different Futures",
      heading: "The certificate, the warranty, and the performance record each do a completely different job after the contract closes. Click each to explore.",
      intro: "",
      image: "three-documents",
      items: [
        { title: "The Acceptance Certificate", text: "Written, dated, signed by the authority the contract names — the document that converts “the buyer seems satisfied” into a legal fact. It starts the warranty clock, releases retainage, and closes the seller's performance obligations." },
        { title: "The Warranty and Defect-Liability Terms", text: "Closure's tail: a defined period during which defects are reported and remedied at the seller's cost, under defined procedures. The closure discipline is to convert those paragraphs into operations — the coverage, the period, the claim procedure, and the contact path written into the operations runbook; the expiry date diarized in the operations calendar; and a named owner, because a warranty nobody monitors is a warranty the organization has silently donated back to the vendor. Where a re-test or performance clause exists, its triggers and windows live here too." },
        { title: "The Vendor Performance Record", text: "A structured, factual account of how the seller actually performed — delivery quality against specification, schedule reliability, responsiveness, conduct under dispute, flexibility on change — written now, while the people who lived the contract still remember it. This record is the organization's institutional memory at the next source selection. It's evidence-based and dispassionate: it will be read by evaluators who never met this vendor, years from now, and folklore helps nobody." },
      ],
    },
    {
      id: "archive",
      tab: "Notice & archive",
      type: "reveal",
      kicker: "Screen 4 — Formal Notice and the Archived File",
      headline: "Closure completes with two final acts",
      heading: "Closure completes with two final acts: telling the seller it's over, and building the file that outlives everyone who lived through it.",
      cta: "Reveal the archive",
      image: "formal-notice-archive",
      reveal: {
        title: "Formal Notice and the Archived File",
        text: "Closure completes with a formal written notice to the seller that the contract is closed — typically issued by the procurement/contract administrator through the channel the contract specifies — and the assembly of the complete contract file into the archive: the agreement and every amendment, the change orders approved and declined, the correspondence that matters, the inspection and acceptance evidence, the claims and their settlements, the invoices and payment records, the performance record, and the closure notice itself. The file is the organization's defense in any later dispute, its audit trail for compliance, and its raw material for procurement lessons. PMBOK® 8 treats updated organizational process assets and archived records as explicit closure outputs — and a contract file is the densest, most legally consequential record a project archives. The test of a well-closed contract is the zombie test in reverse: if a question arises in three years — about the warranty, a payment, an IP clause — a stranger should be able to answer it from the file alone, without locating a single member of the original team.",
        image: "formal-notice-archive",
      },
      quiz: {
        question: "Scenario: Three years after a contract closes, a question arises about whether a specific IP clause was ever amended. Everyone who worked on the original project has since left the organization, but the contract file contains the original agreement, every amendment, and the relevant correspondence. What does this scenario best illustrate?",
        answers: [
          "A poorly closed contract, since none of the original team members are available to answer the question",
          "A well-closed contract passing the zombie test in reverse — a stranger can answer the question from the file alone, without locating anyone who was actually there",
          "A gap in the archive, since correspondence should not be considered part of the official contract file",
          "A failure of the vendor performance record specifically, since it should have captured this information",
        ],
        correct: 1,
        correctFeedback: "Correct! This is exactly what a well-closed contract file is built for — the test isn't whether the original team is still around, it's whether a complete stranger can answer the question from the archive alone. That's the zombie test in reverse, passed.",
        incorrectFeedback: "Reconsider — the absence of the original team is precisely the scenario this discipline is designed for, not a failure; correspondence that matters is explicitly part of the archived file; and this is a contract-terms question, not something the vendor performance record was ever meant to capture.",
      },
    },
    {
      id: "exam",
      tab: "Exam lens",
      type: "reveal",
      kicker: "Screen 5 — Synthesis (Exam Lens)",
      headline: "Handing back the keys was never the end.",
      heading: "Back to that move-out one more time — because handing back the keys was never the end. The deposit, the inspection record, and the filed paperwork were always the part that actually protected everyone afterward.",
      cta: "Reveal the exam lens",
      image: "exam-contract-archive",
      reveal: {
        title: "Synthesis (Exam Lens)",
        text: "With work verified and accepted, the final invoice is checked against price and payment terms, the accepted-work record, and the change-order history — with no final payment over an open dispute, and retainage released at acceptance, not held “just in case.” The acceptance certificate converts satisfaction into a legal fact, starting the warranty clock and closing performance obligations. The warranty gets converted into real operations — coverage, period, procedure, contact, expiry, and a named owner. The vendor performance record gets written now, evidence-based and dispassionate, as institutional memory for the next source selection. And closure ends with formal written notice and a complete archived file dense enough that a stranger, years later, could answer any question about the contract without locating a single member of the original team.",
        bullets: [
          "Final invoice checked against price/payment terms, accepted work, and change-order history — no payment over an open dispute",
          "Retainage is released at acceptance — holding it longer is a breach, not caution",
          "Acceptance certificate starts the warranty clock, releases retainage, and closes performance obligations",
          "Warranty terms must be converted into operations: coverage, period, claim procedure, contact path, diarized expiry, and a named owner",
          "The vendor performance record is written immediately, evidence-based and dispassionate — future institutional memory",
          "The archived file must pass the zombie test in reverse: a stranger should be able to answer any question from the file alone, years later",
        ],
        image: "exam-contract-archive",
      },
    },
  ],
};
